version: '3.1'

services:

  mongo:
    image: mongo:latest
    # command: --serviceExecutor adaptive
    container_name: mdb
    restart: always
    env_file:
      - .env
    ports:
    - 27017:27017
    volumes:
    - ./data/:/data/db/
    - ./docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mdb
    ports:
      - 8081:8081
    env_file:
      - .env

  websrv:
    image: imageservice:2.0.4
    container_name: imageservice
    env_file:
      - .env
    ports:
      - 3333:8000
    volumes:
      - .:/imageservice-flask-test
      
