version: '3.1'

services:
  mongo:
    image: mongo:latest
    # command: --serviceExecutor adaptive
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      #- MONGODB_CONNSTRING=mongodb://mongoadmin:secret@

  websrv:
    image: imageservice:2.0.1
    environment:
      - MONGODB_CONNSTRING=mongodb://mongoadmin:secret@mongodb
    ports:
      - 3333:8000
      
